# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/users/orders' do
  # This should return the minimal set of attributes required to create a valid
  # Users::Order. As you add validations to Users::Order, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Users::Order.create! valid_attributes
      get users_orders_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      order = Users::Order.create! valid_attributes
      get users_order_url(order)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_users_order_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      order = Users::Order.create! valid_attributes
      get edit_users_order_url(order)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Users::Order' do
        expect do
          post users_orders_url, params: { users_order: valid_attributes }
        end.to change(Users::Order, :count).by(1)
      end

      it 'redirects to the created users_order' do
        post users_orders_url, params: { users_order: valid_attributes }
        expect(response).to redirect_to(users_order_url(Users::Order.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Users::Order' do
        expect do
          post users_orders_url, params: { users_order: invalid_attributes }
        end.not_to change(Users::Order, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post users_orders_url, params: { users_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested users_order' do
        order = Users::Order.create! valid_attributes
        patch users_order_url(order), params: { users_order: new_attributes }
        order.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the users_order' do
        order = Users::Order.create! valid_attributes
        patch users_order_url(order), params: { users_order: new_attributes }
        order.reload
        expect(response).to redirect_to(users_order_url(order))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        order = Users::Order.create! valid_attributes
        patch users_order_url(order), params: { users_order: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested users_order' do
      order = Users::Order.create! valid_attributes
      expect do
        delete users_order_url(order)
      end.to change(Users::Order, :count).by(-1)
    end

    it 'redirects to the users_orders list' do
      order = Users::Order.create! valid_attributes
      delete users_order_url(order)
      expect(response).to redirect_to(users_orders_url)
    end
  end
end
