# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/users/products' do
  # This should return the minimal set of attributes required to create a valid
  # Users::Product. As you add validations to Users::Product, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Users::Product.create! valid_attributes
      get users_products_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      product = Users::Product.create! valid_attributes
      get users_product_url(product)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_users_product_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      product = Users::Product.create! valid_attributes
      get edit_users_product_url(product)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Users::Product' do
        expect do
          post users_products_url, params: { users_product: valid_attributes }
        end.to change(Users::Product, :count).by(1)
      end

      it 'redirects to the created users_product' do
        post users_products_url, params: { users_product: valid_attributes }
        expect(response).to redirect_to(users_product_url(Users::Product.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Users::Product' do
        expect do
          post users_products_url, params: { users_product: invalid_attributes }
        end.not_to change(Users::Product, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post users_products_url, params: { users_product: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested users_product' do
        product = Users::Product.create! valid_attributes
        patch users_product_url(product), params: { users_product: new_attributes }
        product.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the users_product' do
        product = Users::Product.create! valid_attributes
        patch users_product_url(product), params: { users_product: new_attributes }
        product.reload
        expect(response).to redirect_to(users_product_url(product))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        product = Users::Product.create! valid_attributes
        patch users_product_url(product), params: { users_product: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested users_product' do
      product = Users::Product.create! valid_attributes
      expect do
        delete users_product_url(product)
      end.to change(Users::Product, :count).by(-1)
    end

    it 'redirects to the users_products list' do
      product = Users::Product.create! valid_attributes
      delete users_product_url(product)
      expect(response).to redirect_to(users_products_url)
    end
  end
end
